### ISSUE TITLE
Admin broken in 1.9.2.2

### ISSUE THREAD

**Issue by TimVroom** [ICEPAYdev/Magento#10]
Hi icepay,

On the new (upcomming) release of patch SUPEE-6788 / 1.9.2.2 your extension is going to break.

https://info2.magento.com/rs/318-XBX-392/images/SUPEE-6788-Technical%20Details.pdf?mkt_tok=3RkMMJWWfF9wsRolv6jPZKXonjHpfsX66e0vXa%2B2lMI%2F0ER3fOvrPUfGjI4CSMFjI%2BSLDwEYGJlv6SgFSbHNMbhiwrgOUhM%3D

Its quite the work to fix this, because every adminhtml controller have to be moved to its proper location. Should be fixed asap. If everything is configured properly its no problem, but when you want to change something its done for.

Good luck

**Comment by tsygankov** [comment]
Dear Tim,

Thank you very much for notifying us and for your contribution to the project!

Release 1.2.11 is now available at the release list and at Magento Connect.
